name: ci
on: [push, pull_request]
jobs:
  pipeline-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pip install typer[all] pyyaml pytest
      - run: python pipeline.py all --fast 1000
